name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build. -t files && docker login -u admin44449999 -p Aaryanaryan && docker tag files admin44449999/files && docker push admin44449999/files
